# Importing the libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

In [7]:
df=pd.read_csv("toy_dataset.csv")

# Getting Information of Dataframe

In [8]:
df.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Number   150000 non-null  int64
 1   City     150000 non-null  object
 2   Gender   150000 non-null  object
 3   Age      150000 non-null  int64
 4   Income   150000 non-null  float64
 5   Illness  150000 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 6.9+ MB

In [10]:
df.describe

<bound method NDFrame.describe of         Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
...        ...     ...     ...  ...       ...     ...
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]>

In [11]:
df.isnull().sum()

Number     0
City       0
Gender     0
Age        0
Income     0
Illness    0
dtype: int64

# Filling the missing data

In [12]:
df=df.dropna()

#Defining X and y

In [13]:
df.columns

Index(['Number', 'City', 'Gender', 'Age', 'Income', 'Illness'], dtype='object')

In [14]:
X=df[['City', 'Gender', 'Income', 'Illness']]
y=df['Age']

# Ordinal Encoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
X[['City', 'Gender','Illness']]=oe.fit_transform(X[['City', 'Gender','Illness']])

#Getting Train Test Split

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,stratify=y,random_state=2)

In [17]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((120000, 4), (30000, 4), (120000,), (30000,))

# Linear Regression

In [18]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [19]:
y_pred=lr.predict(X_test)

In [20]:
from sklearn.metrics import mean_absolute_error

In [21]:
mean_absolute_error(y_test,y_pred)

10.015156026500074